#!/usr/bin/env python3

import os

print("Content-Type: text/html\r")
print("\r") # This blank line is crucial, separates headers from body

print("<html>")
print("<head><title>My CGI Test</title></head>")
print("<body>")
print("<h1>Hello from CGI!</h1>")
print("<p>This page was generated by a Python script.</p>")

print("<h2>Environment Variables Received:</h2>")
print("<ul>")
for key, value in os.environ.items():
    print(f"<li><strong>{key}:</strong> {value}</li>")
print("</ul>")

print("<h2>Request Method:</h2>")
print(f"<p>Method: {os.environ.get('REQUEST_METHOD', 'N/A')}</p>")

print("<h2>Query String:</h2>")
print(f"<p>Query: {os.environ.get('QUERY_STRING', 'N/A')}</p>")

print("</body>")
print("</html>")